n1 = int(input('Escreva um número inteiro:'))
n2 = int(input('Escreva outro número inteiro:'))
n3 = float(input('Escreva um número real:'))
produto = ((n1*2)+(4/2))
print (f' O produto do dobro do primeiro com a metade do segundo é: {produto}')
soma = ((n1*3)+6)
print (f' A soma do triplo do primeiro com o terceiro é: {soma}')
cubo = (6**3)
print (f' O terceiro elevado ao cubo é: {cubo}')
