n1 = int(input('escreva um número inteiro:'))
n2 = int(input('escreva outro número inteiro:'))
n3 = int(input('escreva um número real:'))
produto = ((n1*2)+(4/2))
print (f' o produto do dobro do primeiro com a metade do segundo é:',produto)
soma = ((n1*3)+6)
print (f' a soma do triplo do primeiro com o terceiro é:',soma)
cubo = (6**3)
print (f' o terceiro elevado ao cubo é:',cubo) 
