n1 = int(input('Escreva um número inteiro:'))
n2 = int(input('Escreva outro número inteiro:'))
n3 = float(input('Escreva um número real:'))
produto = ((n1*2)+(n2/2))
print (f' O produto do dobro do primeiro com a metade do segundo é: {produto:.2f}')
soma = ((n1*3)+n3)
print (f' A soma do triplo do primeiro com o terceiro é: {soma:.2f}')
cubo = (n3**3)
print (f' O terceiro elevado ao cubo é: {cubo:.2f}')
