altura_homem = int(input('informe a altura em centimetros do homem:'))
altura_mulher = int(input('informe a altura em centimetros da mulher:'))
peso_homem = ((72.7*190)-58)
print (f'o peso ideal para o homem é:',peso_homem)
peso_mulher = ((62.1*160)-44.7)
print(f' o peso ideal para mulher é:',peso_mulher)
