altura_homem = int(input('Informe a altura em centimetros do homem:'))
altura_mulher = int(input('Informe a altura em centimetros da mulher:'))
peso_homem = ((72.7*altura_homem/100)-58)
print (f'O peso ideal para o homem é {peso_homem} kg')
peso_mulher = ((62.1*altura_mulher/100)-44.7)
print(f'O peso ideal para mulher é {peso_mulher} kg')
